"""initial schema

Revision ID: 04577db2bf10
Revises: 
Create Date: 2026-02-26 08:41:50.903181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04577db2bf10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('client_type', sa.String(length=20), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_client', schema=None) as batch_op:
        batch_op.create_index('ix_download_client_protocol', ['protocol'], unique=False)
        batch_op.create_index('ix_download_client_type', ['client_type'], unique=False)

    op.create_table('indexer_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('categories', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cache_key', sa.String(length=500), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'cache_key', name='uq_metadata_cache_provider_key')
    )
    with op.batch_alter_table('metadata_cache', schema=None) as batch_op:
        batch_op.create_index('ix_metadata_cache_expires', ['expires_at'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('settings', sa.Text(), nullable=False),
    sa.Column('on_grab', sa.Boolean(), nullable=False),
    sa.Column('on_download', sa.Boolean(), nullable=False),
    sa.Column('on_import', sa.Boolean(), nullable=False),
    sa.Column('on_upgrade', sa.Boolean(), nullable=False),
    sa.Column('on_error', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cutoff', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('root_folder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('magazine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_slug', sa.String(length=255), nullable=False),
    sa.Column('issn', sa.String(length=9), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('monitoring_start_date', sa.Date(), nullable=True),
    sa.Column('search_terms', sa.String(length=500), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('root_folder_id', sa.Integer(), nullable=False),
    sa.Column('quality_profile_id', sa.Integer(), nullable=False),
    sa.Column('metadata_provider_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_provider', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(), nullable=True),
    sa.Column('last_metadata_refresh', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quality_profile_id'], ['quality_profile.id'], ),
    sa.ForeignKeyConstraint(['root_folder_id'], ['root_folder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issn'),
    sa.UniqueConstraint('title_slug')
    )
    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.create_index('ix_magazine_quality_profile_id', ['quality_profile_id'], unique=False)
        batch_op.create_index('ix_magazine_root_folder_id', ['root_folder_id'], unique=False)

    op.create_table('quality_profile_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quality_profile_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quality_profile_id'], ['quality_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quality_profile_id', 'quality', name='uq_profile_quality')
    )
    with op.batch_alter_table('quality_profile_item', schema=None) as batch_op:
        batch_op.create_index('ix_profile_item_order', ['quality_profile_id', 'sort_order'], unique=False)

    op.create_table('issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('magazine_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('magazine_id', 'number', name='uq_issue_magazine_number')
    )
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_index('ix_issue_magazine_date', ['magazine_id', 'publication_date'], unique=False)
        batch_op.create_index('ix_issue_magazine_id', ['magazine_id'], unique=False)
        batch_op.create_index('ix_issue_status', ['status'], unique=False)

    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('magazine_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('release_title', sa.String(length=500), nullable=False),
    sa.Column('indexer', sa.String(length=100), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.create_index('ix_blocklist_magazine_id', ['magazine_id'], unique=False)
        batch_op.create_index('ix_blocklist_release_title', ['release_title'], unique=False)

    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('magazine_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazine.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('ix_history_date', ['date'], unique=False)
        batch_op.create_index('ix_history_event_date', ['event_type', 'date'], unique=False)
        batch_op.create_index('ix_history_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_history_magazine_id', ['magazine_id'], unique=False)

    op.create_table('issue_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('release_group', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_file')
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_magazine_id')
        batch_op.drop_index('ix_history_event_type')
        batch_op.drop_index('ix_history_event_date')
        batch_op.drop_index('ix_history_date')

    op.drop_table('history')
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.drop_index('ix_blocklist_release_title')
        batch_op.drop_index('ix_blocklist_magazine_id')

    op.drop_table('blocklist')
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index('ix_issue_status')
        batch_op.drop_index('ix_issue_magazine_id')
        batch_op.drop_index('ix_issue_magazine_date')

    op.drop_table('issue')
    with op.batch_alter_table('quality_profile_item', schema=None) as batch_op:
        batch_op.drop_index('ix_profile_item_order')

    op.drop_table('quality_profile_item')
    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.drop_index('ix_magazine_root_folder_id')
        batch_op.drop_index('ix_magazine_quality_profile_id')

    op.drop_table('magazine')
    op.drop_table('root_folder')
    op.drop_table('quality_profile')
    op.drop_table('notification')
    with op.batch_alter_table('metadata_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_metadata_cache_expires')

    op.drop_table('metadata_cache')
    op.drop_table('indexer_config')
    with op.batch_alter_table('download_client', schema=None) as batch_op:
        batch_op.drop_index('ix_download_client_type')
        batch_op.drop_index('ix_download_client_protocol')

    op.drop_table('download_client')
    # ### end Alembic commands ###
